autofit_workspace:
- howtofit/chapter_1_introduction/gaussian.py
- howtofit/chapter_1_introduction/profiles.py
- howtofit/chapter_database/profiles.py
autogalaxy_workspace:
autolens_workspace:
- imaging/advanced/chaining/hyper_mode/extensions.py
autocti_workspace: