autofit:
- howtofit/chapter_1_introduction/gaussian.py
- howtofit/chapter_1_introduction/profiles.py
- howtofit/chapter_database/profiles.py
autogalaxy:
autolens:
- imaging/advanced/chaining/hyper_mode/extensions.py
autocti:
autofit_test:
autolens_test:
BSc_Galaxies_Project: