name: Test

on:
  - push

jobs:
  find_scripts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [scripts, notebooks]
    outputs:
      matrix: ${{ steps.script_matrix.outputs.matrix }}
    steps:
      - name: Checkout AutoFit
        uses: actions/checkout@v2
        with:
          repository: Jammy2211/autofit_workspace
          path: autofit
      - name: Checkout AutoLens
        uses: actions/checkout@v2
        with:
          repository: Jammy2211/autolens_workspace
          path: autolens
      - uses: actions/checkout@v2
        with:
            path: PyAutoBuild
      - name: Make script matrix
        id: script_matrix
        run: |
          matrix="$(./PyAutoBuild/autobuild/script_matrix.py ${{ matrix.directory }} autofit autolens)"
          echo $matrix
          name="${{ matrix.directory }}_matrix"
          echo $name
          echo "::set-output name=$name::$matrix"

  test_scripts_matrix:
    runs-on: ubuntu-latest
    needs:
      - find_scripts
    strategy:
      matrix:
        project:
          ${{ fromJSON(needs.find_scripts.outputs.scripts_matrix) }}
    steps:
      - name: Echo
        run: |
          echo "${{ matrix.project }}"

  test_notebooks_matrix:
      runs-on: ubuntu-latest
      needs:
        - find_scripts
      strategy:
        matrix:
          project:
            ${{ fromJSON(needs.find_scripts.outputs.notebooks_matrix) }}
      steps:
        - name: Echo
          run: |
            echo "${{ matrix.project }}"

