name: Test

on:
  - push

jobs:
  find_scripts:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.script_matrix.outputs.matrix }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          repository: Jammy2211/autofit_workspace
          path: project
      - name: Make script matrix
        id: script_matrix
        run: |
          pushd ../
          pwd
          ls
          pushd ../
          pwd
          ls
          matrix="$(./PyAutoBuild/autobuild/script_matrix.py scripts project)"
          echo "::set-output name=matrix::matrix"

  test_matrix:
    runs-on: ubuntu-latest
    needs:
      - find_scripts
    strategy:
      matrix:
        project:
          ${{ fromJSON(needs.find_scripts.outputs.matrix) }}
    steps:
      - name: Echo
        run: |
          echo "${{ matrix.project }}"

