name: Test

on:
  - push

jobs:
  find_scripts:
    runs-on: ubuntu-latest
#     outputs:
#       version_number: ${{ steps.version_number.outputs.version_number }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          repository: Jammy2211/autofit_workspace
          path: project
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: List directory
        run: |
          python -c 'import os, json; print(json.dumps(os.listdir(".")))'

