name: Test

on:
  - push

jobs:
  find_scripts:
    runs-on: ubuntu-latest
#     outputs:
#       version_number: ${{ steps.version_number.outputs.version_number }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          repository: Jammy2211/autofit_workspace
          path: project
      - name: Install jq
        run: |
          apt install jq
      - name: List directory
        run: |
          ls -d */ | jq -R -s -c 'split("\n")[:-1]'

