name: Test

on:
  - push

jobs:
  find_scripts:
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.list_directories.outputs.directories }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          repository: Jammy2211/autofit_workspace
          path: project
      - name: List directory
        id: list_directories
        run: |
          cd project/scripts
          directories=`ls -d */ | jq -R -s -c 'split("\n")[:-1]'`
          echo "::set-output name=directories::$directories"

  test_matrix:
    runs-on: ubuntu-latest
    needs:
      - find_scripts
    strategy:
      matrix:
        directory:
          ${{ fromJSON(needs.find_scripts.outputs.directories) }}
    steps:
      - name: Echo
        run: |
          echo "${{ matrix.directory }}"

