on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      ref:
        required: true
        type: string
      path:
         required: true
         type: string
      python_version:
         required: true
         type: string
  jobs:
    setup_project:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        with:
            path: PyAutoBuild
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          path: ${{ inputs.path }}
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
        - name: Install optional requirements
          if: test -f "${{ inputs.path }}/optional_requirements.txt"
          run: |
            echo "Installing optional requirements"
            pip install Cython
            python3 -m pip install -r "${{ inputs.path }}/optional_requirements.txt"